### ISSUE TITLE
Don't offer Kite for non-admin users, or make Kite work with non-admin users

### ISSUE THREAD

**Issue by adamsmith** [kiteco/kite-installer#35]
User feedback: 

> Thanks for getting in touch. To be honest, I'm not even sure if Kite is running correctly. I have an admin account and a separate user account. Atom installs under user accounts, so Kite did too. But when I did that, it was reporting an error. Sadly, I don't remember which one.

Seems like we shouldn't offer Kite on macOS to non-admin users.

**Comment by abe33** [comment]
I'll have to look at how we can detect that case, and probably add a new state so that we can notify this issue properly

**Comment by adamsmith** [comment]
^ the other option is to figure out how to make it work for non-admin users.  This may be as simple as not using an absolute path like `/Applications/Kite.app` but I'm not sure.

**Comment by abe33** [comment]
Hmm, maybe we should always install at `~/Applications/Kite.path` so that it only installs for the current user?

**Comment by abe33** [comment]
Ok, this one can finally be closed, given we now check admin privileges in the first step of the install flow.

**Comment by lizhi1989** [comment]
Can kite be offer to non-admin user?

**Comment by chr7** [comment]
I would need to install Kite without admin rights too.
