### ISSUE TITLE
Potential security vulnerabilities?

### ISSUE THREAD

**Issue by adamsmith** [kiteco/kite-installer#68]
![screen shot 2018-08-17 at 11 08 16 am](https://user-images.githubusercontent.com/87728/44281800-da90d700-a20d-11e8-8786-8d234e5ffe85.png)

**Comment by abe33** [comment]
Hi Adam, unfortunately I do not have access to that message on `kite-installer`, I'll need someone to grant me access to it. As far as we're concerned, and if I compare with the same "vulnerabilities" found in `kite-api`, it's always deep buried in the dev dependency graph, which is only there to provide us with test framework and linter (afaik, there's a bunch coming from babel dependencies, babel being used only by the linter). If you give me access to it I can review them and look to fix them (it's still better if we can get rid of these warnings)
